### ISSUE TITLE
Blog Posts should display the date published rather than the last modified date.

### ISSUE THREAD

**Issue by ErikSolveson** [OpenSourceOrg/dotOrg#93] opened 2024-06-14 19:24 UTC
### Description
For all posts we would like the date to be the Publish date of the post rather than the Last modified date (as it currently is). Special care should be taken to ensure this doesn't affect other content types (Pages, licences, meeting minutes, etc.)

https://opensource.org/blog/a-public-forum-to-discuss-the-open-source-ai-definition

### Steps to reproduce

One Example:
1. https://opensource.org/blog/a-public-forum-to-discuss-the-open-source-ai-definition
2. The date on this post should be Jan 26th. Currently it reads april 11th. 
<img width="2013" alt="Screenshot 2024-06-14 at 1 23 44 PM" src="https://github.com/OpenSourceOrg/dotOrg/assets/25552931/1cd2f490-cac2-4998-8879-fba68c974fc7">

### Places where the date shows.
- In the post itself.
- In the post feed.
- In Jetpack search the correct date is already shown (https://opensource.org/?s=public%20forum)

[[Zendesk](https://a8c.zendesk.com/agent/tickets/8332634)]

**Comment by geoffguillain** [comment] 2024-06-15 04:26
Hey @ErikSolveson,

I have a fix for this but I don't have commit rights on this repo yet, I will ask to be added to create a pull request.

Here are the templates that will be updated:
1. single blog post: https://opensource.org/blog/a-public-forum-to-discuss-the-open-source-ai-definition
2. archive page for posts: https://opensource.org/blog/page/4

Dates on the post feed are looking good to me: https://opensource.org/feed

[Press mentions](https://opensource.org/press-mentions/open-source-ai-osi-wrestles-with-a-definition) are also using the updated dates. Do you want to display the created date for those too?

**Comment by ErikSolveson** [comment] 2024-06-17 15:11
Hi @geoffguillain -

>  [Press mentions](https://opensource.org/press-mentions/open-source-ai-osi-wrestles-with-a-definition) are also using the updated dates. Do you want to display the created date for those too?

No lets keep Press as last modified, they clarified that specifically Posts should be Published date and the others should remain unchanged. 

Thanks!

**Comment by geoffguillain** [comment] 2024-06-18 02:17
Hey @ErikSolveson 

I have updated the blog post single and archive pages to display the published date instead of the updated date.
eg. https://open-source-initiative-development.mystagingwebsite.com/blog/open-source-ai-definition-weekly-update-mar-11

Please take a look and let me know if you have any questions.

**Comment by moyvincent** [comment] 2024-06-18 15:14
Hi @geoffguillain, Thanks for this!

I just checked the Licenses and the Press section to make sure that those still show the "last modified". 

I Tested this out by updating a [test license](https://open-source-initiative-development.mystagingwebsite.com/wp-admin/post.php?post=21868&action=edit) and noticed that it shows the "published" which I think should be "last modified".

> Special care should be taken to ensure this doesn't affect other content types (Pages, licenses, meeting minutes, etc.)

Can you please confirm if the fix must have affected the Pages, licenses, meeting minutes, etc?

Thank you.

**Comment by geoffguillain** [comment] 2024-06-19 05:05
Hey @moyvincent, 

I had a look at your test but I can't see any dates displayed. Could you be more precise about what you are seeing? 

If you talk about the listing pages in the admin, they are displaying the published date since this is the default behavior on those admin pages for published posts. `Draft` on their side shows the Last modified date. I have not touched this core behavior in any way.
eg.: 
<img width="938" alt="image" src="https://github.com/OpenSourceOrg/dotOrg/assets/4668242/70416fe6-0941-4a6d-8042-687adcc2b3bb">


The generated HTML that displays dates on posts looks like this:
`<time class="byline--date entry-date published" datetime="YYYYMMDD">_THE DATE_</time>`

I can't see this HTML on the page's code source you are mentioning.

> Can you please confirm if the fix must have affected the Pages, licenses, meeting minutes, etc?

The condition I have added specifically excludes the post type `post` meaning only blog posts can be excluded. I can confirm that any other post types (Pages, licenses, meeting minutes) using this template part won't be affected.

```
$time_string = '<time class="byline--date entry-date published" datetime="%1$s">%2$s</time>';

		// Don't display the updated date for blog posts.
		if ( 'post' !== get_post_type() ) {
			if ( get_the_time( 'U' ) !== get_the_modified_time( 'U' ) ) {
				$time_string .= '<time class="byline--date entry-date published updated" datetime="%3$s">%4$s</time>';
			}
		}
```

**Comment by moyvincent** [comment] 2024-06-19 14:21
Hi @geoffguillain,

Thank you for this!

My understanding of the issue was that these post types (Pages, licenses, meeting minutes), would show "last-modified" on the "Date" column once updated in the WP-admin but I was wrong 😞.

Thank you for clarifying this.

This looks good and we can move this to Production.

**Comment by smaffulli** [comment] 2024-06-19 14:32
`Press mentions` should *not* display last modified.

**Comment by geoffguillain** [comment] 2024-06-21 06:09
The fix has been pushed to production.

eg. 
https://opensource.org/blog/a-public-forum-to-discuss-the-open-source-ai-definition

Other post types are still using the last modified output: 
https://opensource.org/osd

Please take a look and let me know if you have any questions.

**Comment by moyvincent** [comment] 2024-06-24 12:25
Hi @geoffguillain, 

Thank you for looking into this.

I will inform the partner of the change in the Zendesk thread and update back here based on the feedback.

**Comment by moyvincent** [comment] 2024-06-24 14:35
Hi @geoffguillain,

We just got feedback from the partner and they would like to allow the Meeting Minutes to display only the Published date.

Example: https://opensource.org/meeting-minutes/2024-05-17

The example has both the published date and the last modified date.

Thank you.

**Comment by geoffguillain** [comment] 2024-06-27 01:33
Hey @moyvincent 

I have excluded the Meeting minutes for displaying the updated date. 

eg. develop: https://open-source-initiative-development.mystagingwebsite.com/blog/meeting-minutes/2024-01-19

Let me know if I can merge this to the production server.

**Comment by moyvincent** [comment] 2024-06-27 12:42
Thank you @geoffguillain!

We can move this to production.

**Comment by geoffguillain** [comment] 2024-06-28 06:51
The fix has been pushed to production:
https://opensource.org/meeting-minutes/2024-05-17

**Comment by moyvincent** [comment] 2024-06-28 14:21
I have informed the partner about this update and will update here if there is any feedback.

Thanks a lot, @geoffguillain!

**Comment by moyvincent** [comment] 2024-06-28 15:11
Partner confirmed all looks good.
We are goof to close this out!

Thank you @geoffguillain!

**Closed** 2024-07-11 17:50 UTC
